### ISSUE TITLE
Disqus comment block not showing up on production

### ISSUE THREAD

**Issue by haniMerzouki** [le4ker/personal-jekyll-theme#234]
## Disqus comment block not showing up on production

The Disqus comments block works fine when running locally, but is not showing up when deploying to GitHub pages.

## Expected Behavior

expected a nice comments sections 

## Actual Behavior

no comment section, instead the following message is displayed

*We were unable to load Disqus. If you are a moderator please see our troubleshooting guide*

## Steps to Reproduce the Issue

  1. Fork the repo
  2. Make content adjustments
  3. Create your Disqus account for the website
  4. copy the javascript code that you get from Disqus to the comments page located at `/_includes/comments.html` it should look like this with your username instead of mine.

```
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://merzouki-com.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
```
> the code should be copied inside the `if` statement 

```
{% if site.disqus-shortname %}
...
{% endif %}
```

## Specifications

jekyll 3.8.3
chrome browser

**Comment by le4ker** [comment]
@eiselems can you please try to repro this? I don't remember any change in this area, so it should be working without any issues 🤔

**Comment by eiselems** [comment]
I also don't remember doing anything there but lets have a look later.
But for reproduction, I can see it happening here:
https://le4ker.github.io/personal-jekyll-theme/tech/2015/06/27/welcome.html

Maybe it was even a change on their side

**Comment by eiselems** [comment]
@le4ker could you maybe check on the settings of your disqus if you forgot to update the "site URL" after changing your username? Think it used to be https://panossakos.github.io/personal-jekyll-theme/ and now should be https://le4ker.github.io/personal-jekyll-theme/ 

Would be great, easiest way to test it properly. (Easier than creating a fork and then creating a disqus account for it). But I could do that if necessary.

**Comment by le4ker** [comment]
That's a good point. I'll take a look at it! 😄 Thanks Marcus!

**Comment by eiselems** [comment]
Just let me know when you tested it, in case this is also on master I could have a better look with a fork /new disqus account

**Comment by le4ker** [comment]
I haven't managed to test it yet 😓

Do you want to create a disqus account and replace my own with it?

**Comment by eiselems** [comment]
Just realized with my github account it is not really possible to test because I can not properly create github pages for projects anymore. I added a CNAME to my main github pages repo (eiselems.github.io) and it is linking to my own domain. Now everything is linking to a subpath on that domain which is then hitting the eiselems.github.io repo's content and getting a 404.
e.g. https://eiselems.github.io/personal-jekyll-theme/ :(

**Comment by eiselems** [comment]
Update for me it works even with latest master, seems to be either a mis-setup in @haniMerzouki's case.

See it here:
https://www.marcuseisele.com/personal-jekyll-theme/tech/2015/06/27/welcome.html

Steps to make it work:
1. Verify disqus settings
<img width="1178" alt="bildschirmfoto 2018-09-08 um 22 56 03" src="https://user-images.githubusercontent.com/5188694/45258624-eb6edb80-b3ba-11e8-81f1-a5a91f2dd277.png">
2. Fork repository
3. Update _config.yml and replace disqus-shortname in there.
4. git push origin master
5. DONE.

@haniMerzouki you don't need to update anything besides the config in the _config.yml it should be fine.
@le4ker I think you forgot to update the disqus page settings when renaming your github account.
Think there should be still your old "panossakos.github.io" url.
Could you maybe update the settings in your disqus account?

**Comment by eiselems** [comment]
Couldn't reproduce the issue / we fixed it for the repository here
